# Generated by Django 5.1.7 on 2025-05-13 12:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(max_length=100)),
                ('commodity_type', models.CharField(max_length=100)),
                ('forecast_month', models.CharField(max_length=50)),
                ('forecast_year', models.IntegerField()),
                ('forecasted_amount', models.FloatField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('source_data_last_updated', models.DateTimeField()),
            ],
            options={
                'unique_together': {('municipality', 'commodity_type', 'forecast_month', 'forecast_year')},
            },
        ),
        migrations.CreateModel(
            name='CommodityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('average_weight_per_unit_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_name', models.CharField(max_length=100)),
                ('seasonal_months', models.ManyToManyField(blank=True, to='dashboard.month')),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedHarvestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('commodity_type', models.CharField(max_length=255)),
                ('commodity_spec', models.CharField(blank=True, max_length=255, null=True)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_per_unit_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harvest_location', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_verified', models.DateTimeField(default=django.utils.timezone.now)),
                ('prev_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.harvestrecord')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.admininformation')),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedPlantRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_date', models.DateField()),
                ('commodity_type', models.CharField(max_length=255)),
                ('commodity_spec', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('estimated_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plant_municipality', models.CharField(max_length=255)),
                ('min_expected_harvest', models.IntegerField()),
                ('max_expected_harvest', models.IntegerField()),
                ('average_harvest_units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('land_area', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_verified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('prev_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.plantrecord')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.admininformation')),
            ],
        ),
    ]
