# Generated by Django 5.1.7 on 2025-08-04 06:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommodityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('average_weight_per_unit_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_name', models.CharField(max_length=100)),
                ('seasonal_months', models.ManyToManyField(blank=True, to='dashboard.month')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('redirect_url', models.URLField(blank=True, help_text='Custom redirect URL', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accountsinformation')),
                ('linked_plant_record', models.ForeignKey(blank=True, help_text='If notification is related to a specific plant record', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.initplantrecord')),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedHarvestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('commodity_custom', models.CharField(blank=True, max_length=255, null=True)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_per_unit_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_verified', models.DateTimeField(default=django.utils.timezone.now)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.commoditytype')),
                ('harvest_barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.barangayname')),
                ('harvest_municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.municipalityname')),
                ('prev_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.initharvestrecord')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.admininformation')),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedPlantRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_date', models.DateField()),
                ('commodity_custom', models.CharField(blank=True, max_length=255, null=True)),
                ('min_expected_harvest', models.IntegerField()),
                ('max_expected_harvest', models.IntegerField()),
                ('average_harvest_units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_verified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.commoditytype')),
                ('plant_barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.barangayname')),
                ('plant_municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.municipalityname')),
                ('prev_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.initplantrecord')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.admininformation')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('forecast_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('forecast_month', models.IntegerField()),
                ('forecast_year', models.IntegerField()),
                ('forecasted_amount_kg', models.FloatField()),
                ('forecasted_count_units', models.FloatField()),
                ('seasonal_boost_applied', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('source_data_last_updated', models.DateTimeField()),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.barangayname')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.commoditytype')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.admininformation')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.municipalityname')),
            ],
            options={
                'unique_together': {('commodity', 'forecast_month', 'forecast_year', 'municipality', 'barangay')},
            },
        ),
    ]
