# Generated by Django 5.1.7 on 2025-05-10 05:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_admininformation_first_added_and_more'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedharvestrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.admininformation'),
        ),
        migrations.AddField(
            model_name='verifiedplantrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.admininformation'),
        ),
        migrations.AlterField(
            model_name='verifiedplantrecord',
            name='date_verified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
