# Generated by Django 5.1.7 on 2025-05-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifiedharvestrecord',
            name='harvest_location',
        ),
        migrations.RemoveField(
            model_name='verifiedplantrecord',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='verifiedplantrecord',
            name='longitude',
        ),
        migrations.AddField(
            model_name='verifiedharvestrecord',
            name='harvest_barangay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verifiedharvestrecord',
            name='harvest_municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verifiedplantrecord',
            name='plant_barangay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verifiedplantrecord',
            name='plant_municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
