# Generated by Django 5.1.7 on 2025-05-13 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_verifiedharvestrecord_harvest_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastresult',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
