# Generated by Django 5.1.7 on 2025-05-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_verifiedharvestrecord_verified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedplantrecord',
            name='expected_harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
