# Generated by Django 5.1.7 on 2025-08-04 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_commoditytype_delete_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifiedharvestrecord',
            name='harvest_barangay',
        ),
        migrations.RemoveField(
            model_name='verifiedharvestrecord',
            name='harvest_municipality',
        ),
        migrations.RemoveField(
            model_name='verifiedplantrecord',
            name='plant_barangay',
        ),
        migrations.RemoveField(
            model_name='verifiedplantrecord',
            name='plant_municipality',
        ),
    ]
