# Generated by Django 5.1.7 on 2025-05-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_verifiedplantrecord_expected_harvest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedplantrecord',
            name='estimated_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
