# Generated by Django 5.1.7 on 2025-08-10 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_verifiedharvestrecord_harvest_barangay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifiedharvestrecord',
            name='commodity_custom',
        ),
        migrations.RemoveField(
            model_name='verifiedplantrecord',
            name='commodity_custom',
        ),
    ]
