# Generated by Django 5.1.7 on 2025-05-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_verifiedplantrecord_estimated_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedplantrecord',
            name='average_harvest_units',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
