# Generated by Django 5.1.7 on 2025-08-10 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_commoditytype_years_to_mature'),
        ('dashboard', '0004_remove_verifiedharvestrecord_commodity_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedharvestrecord',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.barangayname'),
        ),
        migrations.AddField(
            model_name='verifiedharvestrecord',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.municipalityname'),
        ),
        migrations.AddField(
            model_name='verifiedplantrecord',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.barangayname'),
        ),
        migrations.AddField(
            model_name='verifiedplantrecord',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.municipalityname'),
        ),
    ]
