# Generated by Django 5.1.7 on 2025-05-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_verifiedplantrecord_average_harvest_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedplantrecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verifiedplantrecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
