# Generated by Django 5.1.7 on 2025-08-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastresult',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
