# Generated by Django 5.1.7 on 2025-05-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_verifiedplantrecord_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(max_length=100)),
                ('commodity_type', models.CharField(max_length=100)),
                ('forecast_month', models.CharField(max_length=50)),
                ('forecast_year', models.IntegerField()),
                ('forecasted_amount', models.FloatField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('source_data_last_updated', models.DateTimeField()),
            ],
            options={
                'unique_together': {('municipality', 'commodity_type', 'forecast_month', 'forecast_year')},
            },
        ),
    ]
