# Generated by Django 5.1.7 on 2025-08-12 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_commoditytype_years_to_mature'),
        ('dashboard', '0007_forecastresult_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastresult',
            name='forecast_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.month'),
        ),
    ]
