# Generated by Django 5.1.7 on 2025-08-12 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_commoditytype_years_to_mature'),
        ('dashboard', '0008_alter_forecastresult_forecast_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastresult',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='forecastresult',
            name='generated_by',
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='forecasted_count_units',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ForecastBatch',
            fields=[
                ('batch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.admininformation')),
            ],
        ),
        migrations.AddField(
            model_name='forecastresult',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dashboard.forecastbatch'),
        ),
    ]
