# Generated by Django 5.1.7 on 2025-08-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_commoditytype_years_to_mature'),
        ('dashboard', '0009_remove_forecastresult_generated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forecastresult',
            unique_together={('commodity', 'forecast_month', 'forecast_year', 'municipality')},
        ),
        migrations.RemoveField(
            model_name='forecastresult',
            name='barangay',
        ),
    ]
