# Generated by Django 5.1.7 on 2025-08-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_forecastresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forecastresult',
            unique_together=set(),
        ),
    ]
