# Generated by Django 5.2.6 on 2025-10-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_forecastresult_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastresult',
            name='forecasted_count_units',
        ),
        migrations.RemoveField(
            model_name='forecastresult',
            name='seasonal_boost_applied',
        ),
        migrations.RemoveField(
            model_name='verifiedplantrecord',
            name='average_harvest_units',
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='source_data_last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='verifiedplantrecord',
            name='max_expected_harvest',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='verifiedplantrecord',
            name='min_expected_harvest',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
