# Generated by Django 5.2.7 on 2025-10-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_forecastresult_forecasted_count_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedplantrecord',
            name='average_harvest_units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
