# Generated by Django 5.2.7 on 2025-10-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_verifiedplantrecord_average_harvest_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifiedharvestrecord',
            name='weight_per_unit_kg',
        ),
    ]
