# Generated by Django 5.1.7 on 2025-08-04 06:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('acc_stat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acc_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('account_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AdminInformation',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BarangayName',
            fields=[
                ('barangay_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('barangay', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('month_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MunicipalityName',
            fields=[
                ('municipality_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('municipality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('unit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_abrv', models.CharField(max_length=20)),
                ('unit_full', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccountsInformation',
            fields=[
                ('account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_register_date', models.DateTimeField()),
                ('account_isverified', models.BooleanField(default=False)),
                ('account_verified_date', models.DateTimeField(blank=True, null=True)),
                ('acc_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accountstatus')),
                ('account_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accounttype')),
                ('account_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.admininformation')),
            ],
        ),
        migrations.CreateModel(
            name='CommodityType',
            fields=[
                ('commodity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('average_weight_per_unit_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('seasonal_months', models.ManyToManyField(blank=True, to='base.month')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.unitmeasurement')),
            ],
        ),
        migrations.CreateModel(
            name='FarmLand',
            fields=[
                ('farminfo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estimated_area', models.FloatField(blank=True, null=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.barangayname')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.municipalityname')),
            ],
        ),
        migrations.AddField(
            model_name='barangayname',
            name='municipality_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.municipalityname'),
        ),
        migrations.AddField(
            model_name='admininformation',
            name='municipality_incharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.municipalityname'),
        ),
        migrations.CreateModel(
            name='RecordTransaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_verified', models.DateTimeField(blank=True, null=True)),
                ('plant_status', models.CharField(choices=[('none', 'None'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='none', max_length=10)),
                ('harvest_status', models.CharField(choices=[('none', 'None'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='none', max_length=10)),
                ('location_type', models.CharField(choices=[('farm_land', 'Farm Land'), ('manual', 'Manual Input')], default='manual', max_length=20)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accountsinformation')),
                ('farm_land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.farmland')),
                ('item_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_status', to='base.accountstatus')),
                ('manual_barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.barangayname')),
                ('manual_municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.municipalityname')),
                ('tr_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.admininformation')),
            ],
        ),
        migrations.CreateModel(
            name='initPlantRecord',
            fields=[
                ('plant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('plant_date', models.DateField()),
                ('commodity_custom', models.CharField(blank=True, max_length=255)),
                ('min_expected_harvest', models.IntegerField()),
                ('max_expected_harvest', models.IntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.commoditytype')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.recordtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='initHarvestRecord',
            fields=[
                ('harvest_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('harvest_date', models.DateField()),
                ('commodity_custom', models.CharField(blank=True, max_length=255)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.commoditytype')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.recordtransaction')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.unitmeasurement')),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('userinfo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(blank=True, default='', max_length=255)),
                ('nameextension', models.CharField(blank=True, default='', max_length=10)),
                ('sex', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('emergency_contact_person', models.CharField(max_length=255)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('address_details', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('civil_status', models.CharField(max_length=50)),
                ('rsbsa_ref_number', models.CharField(blank=True, max_length=22, null=True, unique=True, verbose_name='RSBSA Reference Number')),
                ('hasfarmland', models.BooleanField(default=False)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('barangay_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.barangayname')),
                ('municipality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.municipalityname')),
            ],
        ),
        migrations.AddField(
            model_name='farmland',
            name='userinfo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userinformation'),
        ),
        migrations.CreateModel(
            name='AdminUserManagement',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=255)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accounttype')),
                ('target_useracc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userinformation')),
            ],
        ),
        migrations.AddField(
            model_name='admininformation',
            name='userinfo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userinformation'),
        ),
        migrations.AddField(
            model_name='accountsinformation',
            name='userinfo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userinformation'),
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('userlogin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login_date', models.DateTimeField(auto_now_add=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accountsinformation')),
            ],
        ),
    ]
