# Generated by Django 5.1.7 on 2025-05-13 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('account_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AdminInformation',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255)),
                ('first_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('item_status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AccountsInformation',
            fields=[
                ('account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_register_date', models.DateTimeField()),
                ('account_verified_date', models.DateTimeField(blank=True, null=True)),
                ('account_isverified', models.BooleanField(default=False)),
                ('account_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accounttype')),
                ('account_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.admininformation')),
                ('item_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.itemstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(max_length=255)),
                ('tr_verified_date', models.DateTimeField(blank=True, null=True)),
                ('tr_isverified', models.BooleanField(default=False)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accountsinformation')),
                ('item_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_status', to='base.itemstatus')),
                ('tr_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.admininformation')),
            ],
        ),
        migrations.CreateModel(
            name='PlantRecord',
            fields=[
                ('plant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plant_date', models.DateField()),
                ('commodity_type', models.CharField(max_length=255)),
                ('commodity_spec', models.CharField(blank=True, max_length=255)),
                ('expected_harvest_date', models.DateField()),
                ('plant_municipality', models.CharField(max_length=255)),
                ('plant_barangay', models.CharField(blank=True, max_length=255, null=True)),
                ('min_expected_harvest', models.IntegerField()),
                ('max_expected_harvest', models.IntegerField()),
                ('land_area', models.FloatField()),
                ('remarks', models.TextField(blank=True)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('harvest_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('harvest_date', models.DateField()),
                ('commodity_type', models.CharField(max_length=255, null=True)),
                ('commodity_spec', models.CharField(blank=True, max_length=255)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('weight_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harvest_location', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('userinfo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(blank=True, default='', max_length=255)),
                ('nameextension', models.CharField(blank=True, default='', max_length=10)),
                ('sex', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('emergency_contact_person', models.CharField(max_length=255)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('address_details', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('civil_status', models.CharField(max_length=50)),
                ('rsbsa_ref_number', models.CharField(blank=True, max_length=22, null=True, unique=True, verbose_name='RSBSA Reference Number')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='admininformation',
            name='userinfo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userinformation'),
        ),
        migrations.AddField(
            model_name='accountsinformation',
            name='userinfo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userinformation'),
        ),
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('userlogin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login_date', models.DateTimeField(auto_now_add=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accountsinformation')),
            ],
        ),
    ]
