# Generated by Django 5.1.7 on 2025-05-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
