# Generated by Django 5.1.7 on 2025-05-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_harvestrecord_harvest_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantrecord',
            name='land_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
