# Generated by Django 5.1.7 on 2025-08-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_adminusermanagement_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmland',
            name='farmland_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
