# Generated by Django 5.1.7 on 2025-05-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_admininformation_first_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantrecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantrecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
