# Generated by Django 5.1.7 on 2025-05-13 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_plantrecord_latitude_plantrecord_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginlog',
            name='item_status_id',
        ),
    ]
