# Generated by Django 5.1.7 on 2025-08-08 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_farmland_farmland_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordtransaction',
            name='harvest_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harvest_status_transactions', to='base.accountstatus'),
        ),
        migrations.AlterField(
            model_name='recordtransaction',
            name='plant_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_status_transactions', to='base.accountstatus'),
        ),
    ]
