# Generated by Django 5.1.7 on 2025-08-10 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_recordtransaction_harvest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initharvestrecord',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recordtransaction'),
        ),
    ]
