# Generated by Django 5.1.7 on 2025-05-13 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_userloginlog_item_status_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='notes',
        ),
    ]
