# Generated by Django 5.1.7 on 2025-08-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_initharvestrecord_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditytype',
            name='years_to_mature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of years from planting to first harvest', max_digits=4, null=True),
        ),
    ]
