# Generated by Django 5.1.7 on 2025-08-22 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_commoditytype_years_to_mature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordtransaction',
            name='harvest_status',
        ),
        migrations.RemoveField(
            model_name='recordtransaction',
            name='item_status_id',
        ),
        migrations.RemoveField(
            model_name='recordtransaction',
            name='plant_status',
        ),
        migrations.AddField(
            model_name='initharvestrecord',
            name='record_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harvest_status_transactions', to='base.accountstatus'),
        ),
        migrations.AddField(
            model_name='initplantrecord',
            name='record_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_status_transactions', to='base.accountstatus'),
        ),
        migrations.AddField(
            model_name='recordtransaction',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordtransaction',
            name='planting_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='initplantrecord',
            name='max_expected_harvest',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='initplantrecord',
            name='min_expected_harvest',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
