# Generated by Django 5.1.7 on 2025-08-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_recordtransaction_harvest_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoditytype',
            name='unit',
        ),
        migrations.AddField(
            model_name='commoditytype',
            name='years_to_bearfruit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of years from first harvest to the next fruit bearing', max_digits=4, null=True),
        ),
    ]
