# Generated by Django 5.1.7 on 2025-05-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_plantrecord_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestrecord',
            name='commodity_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
