# Generated by Django 5.1.7 on 2025-08-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_commoditytype_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='account_type',
        ),
    ]
