# Generated by Django 5.1.7 on 2025-08-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_accounttype_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='account_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
