# Generated by Django 5.1.7 on 2025-08-26 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_accounttype_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordtransaction',
            name='tr_verified_by',
        ),
        migrations.AddField(
            model_name='initharvestrecord',
            name='date_verified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='initharvestrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.admininformation'),
        ),
        migrations.AddField(
            model_name='initplantrecord',
            name='date_verified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='initplantrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.admininformation'),
        ),
    ]
