# Generated by Django 5.2.7 on 2025-10-04 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_recordtransaction_tr_verified_by_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminusermanagement',
            name='target_useracc',
        ),
        migrations.AddField(
            model_name='adminusermanagement',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='adminusermanagement',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
