# Generated by Django 5.2.7 on 2025-10-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_adminusermanagement_target_useracc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initharvestrecord',
            name='weight_per_unit',
        ),
    ]
