# Generated by Django 5.2.7 on 2025-10-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_increase_contact_number_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
