"""
Django settings for FruitCast project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""


import os, ssl
from urllib.parse import urlparse, parse_qs
from pathlib import Path



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fq@x30e&eeop%xlqhi-^176c9=pum$vn!^k-*t5c*-wi1m^=-r')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG based on environment variable, default to True for local development
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base',
    'dashboard',
    'administrator',
    'storages',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fruitcast.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'base.context_processors.user_role_id',  # Custom context processor pang user role ID
                'base.context_processors.current_year',  # Current year for footer
                'dashboard.context_processors.unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'fruitcast.wsgi.application'


DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    db_info = urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_info.path[1:],
            'USER': db_info.username,
            'PASSWORD': db_info.password,
            'HOST': db_info.hostname,
            'PORT': db_info.port,
            'OPTIONS': {'sslmode': 'require'},
            'CONN_MAX_AGE': 0,  
        }
    }
else:
    # fallback for local dev
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'fruitcast_db'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', '1234'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }

#digitalocean

# redis-broker db for async operation for training models 
# username = default
# password : AVNS_da_lrGLHGi0GOTJrpdv
# host = redis-broker-do-user-24835869-0.e.db.ondigitalocean.com
# port = 25061

AUTH_USER_MODEL = 'base.AuthUser'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#this is for using this model instead of the built-in user model of djangokineme


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'
USE_TZ = True

USE_I18N = True

# digital ocean spaces settings for storing prophet models

# Use the new STORAGES setting for modern Django versions
# Only use S3/DigitalOcean Spaces storage if all required credentials are provided
if all([os.environ.get('AWS_STORAGE_BUCKET_NAME'), 
        os.environ.get('AWS_S3_ENDPOINT_URL'),
        os.environ.get('AWS_ACCESS_KEY_ID'),
        os.environ.get('AWS_SECRET_ACCESS_KEY')]):
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "bucket_name": os.environ.get('AWS_STORAGE_BUCKET_NAME'),
                "endpoint_url": os.environ.get('AWS_S3_ENDPOINT_URL'),
                "access_key": os.environ.get('AWS_ACCESS_KEY_ID'),
                "secret_key": os.environ.get('AWS_SECRET_ACCESS_KEY'),
                "querystring_auth": False,
                "file_overwrite": False,
            }
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        }
    }
else:
    # Fallback to local file storage for development
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": BASE_DIR / "media",
                "base_url": "/media/",
            }
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        }
    }

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/accounts/login/'
# LOGIN_REDIRECT_URL = "/"
LOGIN_REDIRECT_URL = "/accounts/login/success/"
LOGOUT_REDIRECT_URL = '/accounts/login/'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # default
    'base.authentication.EmailAuthBackend',
    'base.authentication.PhoneAuthBackend',
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'eloisamariemsumbad@gmail.com' #this is temporary email for testing
EMAIL_HOST_PASSWORD = 'kzgz vyop djqc bpld'
# EMAIL_HOST_USER = 'fruitcast.bataan@gmail.com'
# EMAIL_HOST_PASSWORD = 'pjxr njjv veck thyz'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Console backend for development/testing when SMTP fails
if DEBUG:
    # Fallback to console backend if SMTP fails
    EMAIL_BACKEND_FALLBACK = 'django.core.mail.backends.console.EmailBackend'


# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND')

# Default to a local Redis for development if environment variables are not set
if not CELERY_BROKER_URL:
    CELERY_BROKER_URL = 'redis://localhost:6379/0'
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

if CELERY_BROKER_URL.startswith('rediss://'):
    parsed_url = urlparse(CELERY_BROKER_URL)
    query_params = parse_qs(parsed_url.query)

    # If the URL already has the parameter, use it
    if 'ssl_cert_reqs' in query_params:
        cert_reqs = query_params['ssl_cert_reqs'][0]
        if cert_reqs == 'CERT_NONE':
            CELERY_BROKER_USE_SSL = {'ssl_cert_reqs': ssl.CERT_NONE}
        elif cert_reqs == 'CERT_OPTIONAL':
            CELERY_BROKER_USE_SSL = {'ssl_cert_reqs': ssl.CERT_OPTIONAL}
        elif cert_reqs == 'CERT_REQUIRED':
            CELERY_BROKER_USE_SSL = {'ssl_cert_reqs': ssl.CERT_REQUIRED}
    else:
        # If not, add the parameter using the recommended method
        CELERY_BROKER_USE_SSL = {'ssl_cert_reqs': ssl.CERT_NONE}

if CELERY_RESULT_BACKEND.startswith('rediss://'):
    parsed_url = urlparse(CELERY_RESULT_BACKEND)
    query_params = parse_qs(parsed_url.query)
    
    if 'ssl_cert_reqs' in query_params:
        cert_reqs = query_params['ssl_cert_reqs'][0]
        if cert_reqs == 'CERT_NONE':
            CELERY_RESULT_BACKEND_USE_SSL = {'ssl_cert_reqs': ssl.CERT_NONE}
        elif cert_reqs == 'CERT_OPTIONAL':
            CELERY_RESULT_BACKEND_USE_SSL = {'ssl_cert_reqs': ssl.CERT_OPTIONAL}
        elif cert_reqs == 'CERT_REQUIRED':
            CELERY_RESULT_BACKEND_USE_SSL = {'ssl_cert_reqs': ssl.CERT_REQUIRED}
    else:
        CELERY_RESULT_BACKEND_USE_SSL = {'ssl_cert_reqs': ssl.CERT_NONE}

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Manila'

# redis-broker string : rediss://default:AVNS_da_lrGLHGi0GOTJrpdv@redis-broker-do-user-24835869-0.e.db.ondigitalocean.com:25061